// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecurityDemo;

#nullable disable

namespace SecurityDemo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("SecurityDemo.Models.SecretNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Olles hemliga recept",
                            OwnerId = "Olle"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Admin: Serverlösenord 'Admin123'",
                            OwnerId = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Sara: Min dagbok",
                            OwnerId = "Sara"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Admin: Mötesanteckningar",
                            OwnerId = "Admin"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Olle: Tandläkare kl 10",
                            OwnerId = "Olle"
                        },
                        new
                        {
                            Id = 6,
                            Content = "Sara: Köp presenter",
                            OwnerId = "Sara"
                        },
                        new
                        {
                            Id = 7,
                            Content = "Admin: Budget 2026",
                            OwnerId = "Admin"
                        },
                        new
                        {
                            Id = 8,
                            Content = "Olle: Kom ihåg mjölk",
                            OwnerId = "Olle"
                        },
                        new
                        {
                            Id = 9,
                            Content = "Sara: Semesterplaner",
                            OwnerId = "Sara"
                        },
                        new
                        {
                            Id = 10,
                            Content = "Admin: Systemfixar",
                            OwnerId = "Admin"
                        });
                });

            modelBuilder.Entity("SecurityDemo.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("userRole")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin",
                            password = "password123",
                            userRole = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Olle",
                            password = "123",
                            userRole = 0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sara",
                            password = "password",
                            userRole = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
